apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y55i938gv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y55i938gv-nodejs 
  name: y55i938gv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: y55i938gv-nodejs 
